### ISSUE TITLE
install successfully, but not find attributes

### ISSUE THREAD

**Issue by pyeap** [fwilliams/point-cloud-utils#16]
>>> import point_cloud_utils as pcu
>>> pcu.
pcu.__class__(          pcu.__eq__(             pcu.__gt__(             pcu.__loader__          pcu.__package__         pcu.__setattr__(        
pcu.__delattr__(        pcu.__file__            pcu.__hash__(           pcu.__lt__(             pcu.__path__            pcu.__sizeof__(         
pcu.__dict__            pcu.__format__(         pcu.__init__(           pcu.__name__            pcu.__reduce__(         pcu.__spec__            
pcu.__dir__(            pcu.__ge__(             pcu.__init_subclass__(  pcu.__ne__(             pcu.__reduce_ex__(      pcu.__str__(            
pcu.__doc__             pcu.__getattribute__(   pcu.__le__(             pcu.__new__(            pcu.__repr__(           pcu.__subclasshook__(   
>>> v, f, n, _ = pcu.read_ply("model.ply")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'point_cloud_utils' has no attribute 'read_ply'
>>> 

I installed it by 'python3 setup.py install --user'.

**Comment by fwilliams** [comment]
Hi, I need more informatioon to diagnose this issue. What OS are you running? What version of Python? Are you running the import from the same Python shell as the one you used to install the package? Could you provide the verbose output from running `setup.py`?

Also, I really recommend using `conda` to install the package instead of running `setup.py` directly. Installation with `conda` should work out of the box. If you really don't want to use `conda`, you can use `pip` via `pip install git+git://github.com/fwilliams/point-cloud-utils` but this is less recommended. See [https://github.com/fwilliams/point-cloud-utils#installation-instructions](https://github.com/fwilliams/point-cloud-utils#installation-instructions) for details.

**Comment by fwilliams** [comment]
Did this help? Is your issue resolved?

**Comment by fwilliams** [comment]
I can't reproduce this issue. I'm closing this due to lack of activity. Feel free to re-open the issue and post more details if you're still experiencing it.

**Comment by hcp6897** [comment]
**Enviroment: Ubuntu 21.10 + python 3.7.11**
**The Error:**

 _x, n = utils.load_point_cloud_by_file_extension(args.mesh_filename, compute_normals=True)
  File "/media/hcp/Master/PhDResearchWork/PointCloud/deep-geometric-prior/utils.py", line 51, in load_point_cloud_by_file_extension
    v, f, n, _ = pcu.read_ply(file_name, dtype=np.float32)
AttributeError: module 'point_cloud_utils' has no attribute 'read_ply'_

**Comment by fwilliams** [comment]
Hi, it looks like you're running a very old build of point_cloud_utils. Try installing the latest:

`pip install git+git://github.com/fwilliams/point-cloud-utils`

**Comment by fwilliams** [comment]
The function `read_ply` does not exist anymore and has been replaced with the [new mesh I.O. functions here](https://github.com/fwilliams/point-cloud-utils#loading-meshes-and-point-clouds)
