### ISSUE TITLE
Compilation error on windows

### ISSUE THREAD

**Issue by nicolocarissimi** [fwilliams/point-cloud-utils#3]
Compilation on windows stops with error

```
CMake Error at external/numpyeigen/cmake/numpyeigen.cmake:85 (warning):
    Unknown CMake command "warning".
```

**Comment by fwilliams** [comment]
What version of CMake are you using?

**Comment by nicolocarissimi** [comment]
3.14

**Comment by fwilliams** [comment]
Could you paste the full output of running CMake on your terminal including the command? I'll take a look.

**Comment by nicolocarissimi** [comment]
Sure, thank you.

```
pip install git+git://github.com/fwilliams/point-cloud-utils
Collecting git+git://github.com/fwilliams/point-cloud-utils
  Cloning git://github.com/fwilliams/point-cloud-utils to c:\users\ncaris~1\appdata\local\temp\pip-req-build-1hh01oq7
Requirement already satisfied: numpy in c:\users\me\appdata\local\programs\python\python35\lib\site-packages (from point-cloud-utils==0.2.0) (1.14.0+mkl)
Requirement already satisfied: scipy in c:\users\me\appdata\local\programs\python\python35\lib\site-packages (from point-cloud-utils==0.2.0) (0.19.0)
Building wheels for collected packages: point-cloud-utils
  Building wheel for point-cloud-utils (setup.py) ... error
  Complete output from command c:\users\me\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\me\\AppData\\Local\\Temp\\pip-req-build-1hh01oq7\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\me\AppData\Local\Temp\pip-wheel-7bco6qt3 --python-tag cp35:
  c:\users\me\appdata\local\programs\python\python35\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_ext
  -- Building for: Visual Studio 14 2015
  -- Selecting Windows SDK version  to target Windows 10.0.10586.
  -- The C compiler identification is MSVC 19.0.24215.1
  -- The CXX compiler identification is MSVC 19.0.24215.1
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at external/numpyeigen/cmake/numpyeigen.cmake:85 (warning):
    Unknown CMake command "warning".
  Call Stack (most recent call first):
    CMakeLists.txt:20 (include)


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/me/AppData/Local/Temp/pip-req-build-1hh01oq7/build/temp.win-amd64-3.5/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\me\AppData\Local\Temp\pip-req-build-1hh01oq7\setup.py", line 98, in <module>
      'scipy'
    File "c:\users\me\appdata\local\programs\python\python35\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\me\appdata\local\programs\python\python35\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\me\appdata\local\programs\python\python35\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\users\me\appdata\local\programs\python\python35\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\me\appdata\local\programs\python\python35\lib\site-packages\wheel\bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "c:\users\me\appdata\local\programs\python\python35\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\me\appdata\local\programs\python\python35\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\me\appdata\local\programs\python\python35\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\me\appdata\local\programs\python\python35\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\me\appdata\local\programs\python\python35\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\me\AppData\Local\Temp\pip-req-build-1hh01oq7\setup.py", line 38, in run
      self.build_extension(ext)
    File "C:\Users\me\AppData\Local\Temp\pip-req-build-1hh01oq7\setup.py", line 64, in build_extension
      subprocess.check_call(['cmake'] + cmake_args + [ext.sourcedir], cwd=self.build_temp, env=env)
    File "c:\users\me\appdata\local\programs\python\python35\lib\subprocess.py", line 581, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\me\\AppData\\Local\\Temp\\pip-req-build-1hh01oq7\\build\\lib.win-amd64-3.5', '-DPYTHON_EXECUTABLE=c:\\users\\me\\appdata\\local\\programs\\python\\python35\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\me\\AppData\\Local\\Temp\\pip-req-build-1hh01oq7\\build\\lib.win-amd64-3.5', '-A', 'x64', 'C:\\Users\\me\\AppData\\Local\\Temp\\pip-req-build-1hh01oq7']' returned non-zero exit status 1
```

**Comment by nicolocarissimi** [comment]
Any news?

**Comment by fwilliams** [comment]
@nicolocarissimi I upgraded the version of [numpyeigen](https://github.com/fwilliams/numpyeigen) to the latest which supports Windows. I think this fixes the bug but I don't have a Windows machine to test on. Can you try and let me know?

**Comment by nicolocarissimi** [comment]
Sorry, @fwilliams, I needed to finish other activities while waiting for this problem to be fixed.
I'll try ASAP and let you know, thanks!

**Comment by fwilliams** [comment]
@nicolocarissimi Any updates?

**Comment by fwilliams** [comment]
There is now a conda-forge package for Windows, so I'm closing this issue. You can install it by simply running

```
conda install -c conda-forge point_cloud_utils
```
