### ISSUE TITLE
Pip3 install point_cloud_utils Error

### ISSUE THREAD

**Issue by LilyGinger** [fwilliams/point-cloud-utils#40]
Thank you very much for your great work. However, I met some problems when I run **pip3 install point_cloud_utils**. We would be grateful if you could help us to find the problem!

Here is the output in the console:

```sh
Building wheel for point-cloud-utils (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/orca/.local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpqzzsiv3a
       cwd: /tmp/pip-install-9dj02x4j/point-cloud-utils_3880d41467d44289b8d9193e8f62e767
  Complete output (60 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.6
  creating build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/__init__.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_octree.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_mesh_io.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_ray_mesh_intersector.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_pointcloud_normals.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_sinkhorn.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_ray_mesh.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  running build_ext
  CMake Error: The source directory "/tmp/pip-install-9dj02x4j/point-cloud-utils_3880d41467d44289b8d9193e8f62e767" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  Traceback (most recent call last):
    File "/home/orca/.local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/orca/.local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/orca/.local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 116, in <module>
      main()
    File "setup.py", line 111, in main
      test_suite="tests"
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-4fp4vm8t/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 39, in run
      self.build_extension(ext)
    File "setup.py", line 71, in build_extension
      subprocess.check_call(['cmake'] + cmake_args + [ext.sourcedir], cwd=self.build_temp, env=env)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-9dj02x4j/point-cloud-utils_3880d41467d44289b8d9193e8f62e767/build/lib.linux-aarch64-3.6/point_cloud_utils', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '/tmp/pip-install-9dj02x4j/point-cloud-utils_3880d41467d44289b8d9193e8f62e767']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for point-cloud-utils
Failed to build point-cloud-utils
ERROR: Could not build wheels for point-cloud-utils, which is required to install pyproject.toml-based projects
```

**Comment by fwilliams** [comment]
Hi, it seems you might be building the library from source!

Try
```
pip install point-cloud-utils
```

(note the dashes (`-`) instead of underscores (`_`))

**Comment by rty813** [comment]
> Hi, it seems you might be building the library from source!
> 
> Try
> 
> ```
> pip install point-cloud-utils
> ```
> 
> (note the dashes (`-`) instead of underscores (`_`))

```
orca@nvidia-desktop ~ [1]> sudo pip install point-cloud-utils
WARNING: The directory '/home/orca/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting point-cloud-utils
  Downloading point-cloud-utils-0.22.0.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scipy in ./.local/lib/python3.6/site-packages (from point-cloud-utils) (1.1.0)
Requirement already satisfied: numpy in ./.local/lib/python3.6/site-packages (from point-cloud-utils) (1.19.4)
Building wheels for collected packages: point-cloud-utils
  Building wheel for point-cloud-utils (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/orca/.local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpmbmrb6yq
       cwd: /tmp/pip-install-5ywts_lp/point-cloud-utils_5034427842f940e5a0392e3a7f9cc7d2
  Complete output (60 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.6
  creating build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/__init__.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_octree.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_mesh_io.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_ray_mesh_intersector.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_pointcloud_normals.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_sinkhorn.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  copying point_cloud_utils/_ray_mesh.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
  running build_ext
  CMake Error: The source directory "/tmp/pip-install-5ywts_lp/point-cloud-utils_5034427842f940e5a0392e3a7f9cc7d2" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  Traceback (most recent call last):
    File "/home/orca/.local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/orca/.local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/orca/.local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 116, in <module>
      main()
    File "setup.py", line 111, in main
      test_suite="tests"
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-pf50uh7l/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 39, in run
      self.build_extension(ext)
    File "setup.py", line 71, in build_extension
      subprocess.check_call(['cmake'] + cmake_args + [ext.sourcedir], cwd=self.build_temp, env=env)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-5ywts_lp/point-cloud-utils_5034427842f940e5a0392e3a7f9cc7d2/build/lib.linux-aarch64-3.6/point_cloud_utils', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '/tmp/pip-install-5ywts_lp/point-cloud-utils_5034427842f940e5a0392e3a7f9cc7d2']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for point-cloud-utils
Failed to build point-cloud-utils
ERROR: Could not build wheels for point-cloud-utils, which is required to install pyproject.toml-based projects
```

**Comment by shihgianlee** [comment]
I am getting the same error.

**Comment by fwilliams** [comment]
@LilyGinger could you also confirm your system details?

Also, I seem to have just fixed the build for macos (see [this commit](https://github.com/fwilliams/point-cloud-utils/commit/b9d625641acdd02ee32668c2876fc09d8a5a847c)). I'll cut a new release and send a ping when the package is deployed!

**Comment by LilyGinger** [comment]
Thank you a lot for your time! 
We are installing it on JETSON XAVIER NX with Ubuntu 16.04, Python 3.6.9, Cmake 3.22.4.

**Comment by fwilliams** [comment]
@LilyGinger 

Ah okay, Xavier NX is an ARM CPU and the current CI pipeline is building x86. 

Like the MacOS issues, this is likely a simple compilation issue. Could you try building the library locally and posting the error. That should help me fix it.

To do that run:
```
git clone git@github.com:fwilliams/point-cloud-utils.git
cd point-cloud-utils
python setup.py build
```

Then paste the output of your shell here.

**Comment by LilyGinger** [comment]
@fwilliams Thank you a lot. Here is the output.

```sh
running build
running build_py
creating build
creating build/lib.linux-aarch64-3.6
creating build/lib.linux-aarch64-3.6/point_cloud_utils
copying point_cloud_utils/__init__.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
copying point_cloud_utils/_octree.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
copying point_cloud_utils/_mesh_io.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
copying point_cloud_utils/_ray_mesh_intersector.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
copying point_cloud_utils/_pointcloud_normals.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
copying point_cloud_utils/_sinkhorn.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
copying point_cloud_utils/_ray_mesh.py -> build/lib.linux-aarch64-3.6/point_cloud_utils
running build_ext
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Cloning into 'numpyeigen'...
Note: checking out '4916d926aa2b939bd8f625c7537563a1575dafe9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 4916d92 update pybind11
-- Performing Test COMPILER_SUPPORT_OPENMP
-- Performing Test COMPILER_SUPPORT_OPENMP - Success
CMake Warning (dev) at external/numpyeigen/cmake/numpyeigen.cmake:98 (set):
  Cannot set "NPE_ROOT_DIR": current scope has no parent.
Call Stack (most recent call first):
  CMakeLists.txt:21 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

Cloning into 'eigen'...
HEAD is now at 21ae2afd4 bump to 3.3.7
Cloning into 'pybind11'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Cloning into 'pybind11'...


Switched to a new branch 'numpy_hacks_stable'
-- pybind11 v2.9.0
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
-- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
Cloning into 'manifold'...
fatal: unable to access 'https://github.com/hjwdzh/Manifold.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
Cloning into 'manifold'...
fatal: unable to access 'https://github.com/hjwdzh/Manifold.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
Cloning into 'manifold'...
Note: checking out '81fd342e578e29fc15fb75d2b4d1e3c821fe33cb'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 81fd342 Update README.md
Cloning into 'embree'...

Note: checking out 'v3.12.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 69bd4c272 regenerated documentation
-- Found Git: /usr/bin/git (found version "2.17.1")
-- Detecting default ISA...
-- Detected default ISA: SSE2
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Using local options file: /home/orca/zbz/point-cloud-utils/external/geogram/CMakeOptions.txt
-- Configuring build for standalone Geogram (without Vorpaline)
-- GCC version >= 4.3, activating sign conversion warnings
-- GCC version >= 4.6, activating double promotion warnings
-- Doxygen >= 1.7.0 not found, cannot generate documentation
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/orca/zbz/point-cloud-utils/build/temp.linux-aarch64-3.6
Scanning dependencies of target manifold
Scanning dependencies of target npe
[  0%] Building CXX object CMakeFiles/npe.dir/external/numpyeigen/src/npe_typedefs.cpp.o
[  1%] Building CXX object CMakeFiles/manifold.dir/external/manifold/src/BVH.cpp.o
<command-line>:0:15: warning: missing terminating " character
<command-line>:0:0: warning: "VERSION_INFO" redefined
<command-line>:0:0: note: this is the location of the previous definition
[  1%] Building CXX object CMakeFiles/manifold.dir/external/manifold/src/Intersection.cpp.o
<command-line>:0:15: warning: missing terminating " character
<command-line>:0:0: warning: "VERSION_INFO" redefined
<command-line>:0:0: note: this is the location of the previous definition
[  2%] Building CXX object CMakeFiles/manifold.dir/external/manifold/src/main.cpp.o
<command-line>:0:15: warning: missing terminating " character
<command-line>:0:0: warning: "VERSION_INFO" redefined
<command-line>:0:0: note: this is the location of the previous definition
In file included from /home/orca/zbz/point-cloud-utils/external/numpyeigen/src/npe_typedefs.h:6:0,
                 from /home/orca/zbz/point-cloud-utils/external/numpyeigen/src/npe_typedefs.cpp:1:
/home/orca/zbz/point-cloud-utils/external/numpyeigen/cmake/../src/npe_sparse_array.h:17:8: warning: ‘npe::sparse_array’ declared with greater visibility than the type of its field ‘npe::sparse_array::<anonymous>’ [-Wattributes]
 struct sparse_array : pybind11::object {
        ^~~~~~~~~~~~
/home/orca/zbz/point-cloud-utils/external/numpyeigen/cmake/../src/npe_sparse_array.h:17:8: warning: ‘npe::sparse_array’ declared with greater visibility than its base ‘pybind11::object’ [-Wattributes]
[  2%] Building CXX object CMakeFiles/manifold.dir/external/manifold/src/Model_OBJ.cpp.o
<command-line>:0:15: warning: missing terminating " character
<command-line>:0:0: warning: "VERSION_INFO" redefined
<command-line>:0:0: note: this is the location of the previous definition
[  3%] Linking CXX static library libnpe.a
[  3%] Built target npe
Scanning dependencies of target geogram_third_party
[  3%] Building C object geogram/src/lib/geogram/third_party/CMakeFiles/geogram_third_party.dir/LM7/libmeshb7.c.o
cc: error: unrecognized command line option ‘-m64’
geogram/src/lib/geogram/third_party/CMakeFiles/geogram_third_party.dir/build.make:62: recipe for target 'geogram/src/lib/geogram/third_party/CMakeFiles/geogram_third_party.dir/LM7/libmeshb7.c.o' failed
make[2]: *** [geogram/src/lib/geogram/third_party/CMakeFiles/geogram_third_party.dir/LM7/libmeshb7.c.o] Error 1
CMakeFiles/Makefile2:780: recipe for target 'geogram/src/lib/geogram/third_party/CMakeFiles/geogram_third_party.dir/all' failed
make[1]: *** [geogram/src/lib/geogram/third_party/CMakeFiles/geogram_third_party.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Linking CXX static library libmanifold.a
[  3%] Built target manifold
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    main()
  File "setup.py", line 111, in main
    test_suite="tests"
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 72, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.

**Comment by shihgianlee** [comment]
> @shihgianlee MacOS support should be live now. Can you try to `pip install point-cloud-utils` on your mac?

@fwilliams The installation is successful! Thank you very much for the fix!

**Comment by fwilliams** [comment]
@LilyGinger I think your issue might be fairly straightforward to fix. I'll give it a shot soon. I'm closing this issue and opening #41 for your specific problem

**Comment by LilyGinger** [comment]
@fwilliams Hi, we are very sorry to bother you again. 
We are wondering when the #41 could be fixed. We hope to use some of the functions in point_cloud_utils in our group project recently. We would be thankful if you cloud help us in installing and we are always ready for the required operations if you need to test something.

**Comment by fwilliams** [comment]
@LilyGinger Moving this chat to #41: See the discussion there
