### ISSUE TITLE
Error while running pip3 install point-cloud-utils on Windows 10

### ISSUE THREAD

**Issue by utacc** [fwilliams/point-cloud-utils#93]
When attempting to install point-cloud-utils, I get the following error message(s), both as my regular user, and as Admin:

Microsoft Windows [Version 10.0.22631.3737]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>pip3 install point-cloud-utils
Collecting point-cloud-utils
  Using cached point-cloud-utils-0.30.4.tar.gz (46 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\python312\lib\site-packages (from point-cloud-utils) (2.0.0)
Requirement already satisfied: scipy in c:\python312\lib\site-packages (from point-cloud-utils) (1.13.1)
Building wheels for collected packages: point-cloud-utils
  Building wheel for point-cloud-utils (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for point-cloud-utils (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [79 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\point_cloud_utils
      copying point_cloud_utils\_mesh_io.py -> build\lib.win-amd64-cpython-312\point_cloud_utils
      copying point_cloud_utils\_mesh_primitives.py -> build\lib.win-amd64-cpython-312\point_cloud_utils
      copying point_cloud_utils\_pointcloud_normals.py -> build\lib.win-amd64-cpython-312\point_cloud_utils
      copying point_cloud_utils\_point_cloud_geometry.py -> build\lib.win-amd64-cpython-312\point_cloud_utils
      copying point_cloud_utils\_ray_mesh_intersector.py -> build\lib.win-amd64-cpython-312\point_cloud_utils
      copying point_cloud_utils\_ray_point_cloud_intersector.py -> build\lib.win-amd64-cpython-312\point_cloud_utils
      copying point_cloud_utils\_sinkhorn.py -> build\lib.win-amd64-cpython-312\point_cloud_utils
      copying point_cloud_utils\_voxels.py -> build\lib.win-amd64-cpython-312\point_cloud_utils
      copying point_cloud_utils\__init__.py -> build\lib.win-amd64-cpython-312\point_cloud_utils
      running build_ext
      <string>:34: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      CMake Warning:
        Ignoring extra path from command line:

         "C:\Users\furys\AppData\Local\Temp\pip-install-kmohnaca\point-cloud-utils_c2792ebdb0b0404cbf73ef28204b40b1"

      CMake Error: The source directory "C:/Users/furys/AppData/Local/Temp/pip-install-kmohnaca/point-cloud-utils_c2792ebdb0b0404cbf73ef28204b40b1" does not appear to contain CMakeLists.txt.
      Specify --help for usage, or press the help button on the CMake GUI.
      64 bit!
      Traceback (most recent call last):
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 116, in <module>
        File "<string>", line 89, in main
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\command\bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\dist.py", line 976, in run_command
          super().run_command(command)
        File "C:\Users\furys\AppData\Local\Temp\pip-build-env-juueg2qa\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 39, in run
        File "<string>", line 71, in build_extension
        File "C:\Python312\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\furys\\AppData\\Local\\Temp\\pip-install-kmohnaca\\point-cloud-utils_c2792ebdb0b0404cbf73ef28204b40b1\\build\\lib.win-amd64-cpython-312\\point_cloud_utils', '-DPYTHON_EXECUTABLE=C:\\Python312\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\furys\\AppData\\Local\\Temp\\pip-install-kmohnaca\\point-cloud-utils_c2792ebdb0b0404cbf73ef28204b40b1\\build\\lib.win-amd64-cpython-312\\point_cloud_utils', '-A', 'x64', 'C:\\Users\\furys\\AppData\\Local\\Temp\\pip-install-kmohnaca\\point-cloud-utils_c2792ebdb0b0404cbf73ef28204b40b1']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for point-cloud-utils
Failed to build point-cloud-utils
ERROR: Could not build wheels for point-cloud-utils, which is required to install pyproject.toml-based projects

C:\Windows\System32>

**Comment by BryanCastro** [comment]
Doesn't support Python 3.12, try 3.11 instead then: py -m pip install point-cloud-utils --timeout 5000
